SELECT * FROM PoGoDex.dbo.Dex
ORDER BY Pkmn_Id;

--Region 1 Pokemon name entry, new evolution chain on each row
INSERT INTO dbo.Dex (Pkmn_Name) VALUES 
	('Bulbasaur'),('Ivysaur'),('Venusaur'),
	('Charmander'),('Charmeleon'),('Charizard'),
	('Squirtle'),('Wartortle'),('Blastoise'),
	('Caterpie'),('Metapod'),('Butterfree'),
	('Weedle'),('Kakuna'),('Beedrill'),
	('Pidgey'),('Pidgeotto'),('Pidgeot'),
	('Rattata'),('Raticate'),
	('Spearow'),('Fearow'),
	('Ekans'),('Arbok'),
	('Pikachu'),('Raichu'),
	('Sandshrew'),('Sandslash'),
	('NidoranF'),('Nidorina'),('Nidoqueen'),
	('NidoranM'),('Nidorino'),('Nidoking'),
	('Clefairy'),('Clefable'),
	('Vulpix'),('Ninetales'),
	('Jigglypuff'),('Wigglytuff'),
	('Zubat'),('Golbat'),
	('Oddish'),('Gloom'),('Vileplume'),
	('Paras'),('Parasect'),
	('Venonat'),('Venomoth'),
	('Diglett'),('Dugtrio'),
	('Meowth'),('Persian'),
	('Psyduck'),('Golduck'),
	('Mankey'),('Primeape'),
	('Growlithe'),('Arcanine'),
	('Poliwag'),('Poliwhirl'),('Poliwrath'),
	('Abra'),('Kadabra'),('Alakazam'),
	('Machop'),('Machoke'),('Machamp'),
	('Bellsprout'),('Weepinbell'),('Victreebel'),
	('Tentacool'),('Tentacruel'),
	('Geodude'),('Graveler'),('Golem'),
	('Ponyta'),('Rapidash'),
	('Slowpoke'),('Slowbro'),
	('Magnemite'),('Magneton'),
	('Farfetchd'),
	('Doduo'),('Dodrio'),
	('Seel'),('Dewgong'),
	('Grimer'),('Muk'),
	('Shellder'),('Cloyster'),
	('Gastly'),('Haunter'),('Gengar'),
	('Onix'),
	('Drowzee'),('Hypno'),
	('Krabby'),('Kingler'),
	('Voltorb'),('Electrode'),
	('Exeggcute'),('Exeggutor'),
	('Cubone'),('Marowak'),
	('Hitmonlee'),
	('Hitmonchan'),
	('Lickitung'),
	('Koffing'),('Weezing'),
	('Rhyhorn'),('Rhydon'),
	('Chansey'),
	('Tangela'),
	('Kangaskhan'),
	('Horsea'),('Seadra'),
	('Goldeen'),('Seaking'),
	('Staryu'),('Starmie'),
	('Mr. Mime'),
	('Scyther'),
	('Jynx'),
	('Electabuzz'),
	('Magmar'),
	('Pinsir'),
	('Tauros'),
	('Magikarp'),('Gyarados'),
	('Lapras'),
	('Ditto'),
	('Eevee'),('Vaporeon'),
		  ('Jolteon'),
	          ('Flareon'),
	('Porygon'),
	('Omanyte'),('Omastar'),
	('Kabuto'),('Kabutops'),
	('Aerodactyl'),
	('Snorlax'),
	('Articuno'),
	('Zapdos'),
	('Moltres'),
	('Dratini'),('Dragonair'),('Dragonite'),
	('Mewtwo'),
	('Mew');

-- Drop & Change constraint when entering data for new region
ALTER TABLE Dex
	DROP CONSTRAINT DF__Dex__Reg_Id__4F7CD00D;

ALTER TABLE Dex  
    ADD CONSTRAINT DF__Dex__Reg_Id__4F7CD00D 
    DEFAULT 2 FOR Reg_Id;

--Region 2 Pokemon name entry, new evolution chain on each row
INSERT INTO dbo.Dex (Pkmn_Name) VALUES 
	('Chikorita'),('Bayleef'),('Meganium'),
	('Cyndaquil'),('Quilava'),('Typlosion'),
	('Totodile'),('Croconaw'),('Feraligatr'),
	('Sentret'),('Furret'),
	('Hoothoot'),('Noctowl'),
	('Ledyba'),('Ledian'),
	('Spinarak'),('Ariados'),
	('Crobat'),
	('Chinchou'),('Lanturn'),
	('Pichu'),
	('Cleffa'),
	('Igglybuff'),
	('Togepi'),('Togetic'),
	('Natu'),('Xatu'),
	('Mareep'),('Flaaffy'),('Ampharos'),
	('Bellossom'),
	('Marill'),('Azumarill'),
	('Sudowoodo'),
	('Politoed'),
	('Hoppip'),('Skiploom'),('Jumpluff'),
	('Aipom'),
	('Sunkern'),('Sunflora'),
	('Yanma'),
	('Wooper'),('Quagsire'),
	('Espeon'),
	('Umbreon'),
	('Murkrow'),
	('Slowking'),
	('Misdreavus'),
	('Unknown'),
	('Wobbuffet'),
	('Girafarig'),
	('Pineco'),('Forretress'),
	('Dunsparce'),
	('Gligar'),
	('Steelix'),
	('Snubbull'),('Granbull'),
	('Qwilfish'),
	('Scizor'),
	('Shuckle'),
	('Heracross'),
	('Sneasel'),
	('Teddiursa'),('Ursaring'),
	('Slugma'),('Magcargo'),
	('Swinub'),('Piloswine'),
	('Corsola'),
	('Remoraid'),('Octillery'),
	('Delibird'),
	('Mantine'),
	('Skarmory'),
	('Houndour'),('Houndoom'),
	('Kingdra'),
	('Phanpy'),('Donphan'),
	('Porygon2'),
	('Stantler'),
	('Smeargle'),
	('Tyrogue'),('Hitmontop'),
	('Smoochum'),
	('Elekid'),
	('Magby'),
	('Miltank'),
	('Blissey'),
	('Raikou'),
	('Entei'),
	('Suicune'),
	('Larvitar'),('Pupitar'),('Tyranitar'),
	('Lugia'),
	('Ho-oh'),
	('Celebi');

-- Drop & Change constraint when entering data for new region
ALTER TABLE Dex
	DROP CONSTRAINT DF__Dex__Reg_Id__4F7CD00D;

ALTER TABLE Dex  
    ADD CONSTRAINT DF__Dex__Reg_Id__4F7CD00D 
    DEFAULT 3 FOR Reg_Id;

--Region 3 Pokemon name entry, new evolution chain on each row
INSERT INTO dbo.Dex (Pkmn_Name) VALUES 
	('Treecko'),('Grovyle'),('Sceptile'),
	('Torchic'),('Combusken'),('Blaziken'),
	('Mudkip'),('Marshtomp'),('Swampert'),
	('Poochyena'),('Mightyena'),
	('Zigzagoon'),('Linoone'),
	('Wurmple'),('Silcoon'),('Beautifly'),
		    ('Cascoon'),('Dustox'),
	('Lotad'),('Lombre'),('Ludicolo'),
	('Seedot'),('Nuzleaf'),('Shiftry'),
	('Taillow'),('Swellow'),
	('Wingull'),('Pelipper'),
	('Ralts'),('Kirlia'),('Gardevoir'),
	('Surskit'),('Masquerain'),
	('Shroomish'),('Breloom'),
	('Slakoth'),('Vigoroth'),('Slaking'),
	('Nincada'),('Ninjask'),
		    ('Shedinja'),
	('Whismur'),('Loudred'),('Exploud'),
	('Makuhita'),('Hariyama'),
	('Azurill'),
	('Nosepass'),
	('Skitty'),('Delcatty'),
	('Sableye'),
	('Mawile'),
	('Aron'),('Lairon'),('Aggron'),
	('Meditite'),('Medicham'),
	('Electrike'),('Manetric'),
	('Plusle'),
	('Minun'),
	('Volbeat'),
	('Illumise'),
	('Roselia'),
	('Gulpin'),('Swalot'),
	('Carvanha'),('Sharpedo'),
	('Wailmer'),('Wailord'),
	('Numel'),('Camerupt'),
	('Torkoal'),
	('Spoink'),('Grumpig'),
	('Spinda'),
	('Trapinch'),('Vibrava'),('Flygon'),
	('Cacnea'),('Cacturne'),
	('Swablu'),('Altaria'),
	('Zangoose'),
	('Seviper'),
	('Lunatone'),
	('Solrock'),
	('Barboach'),('Whiscash'),
	('Corphish'),('Crawdaunt'),
	('Baltoy'),('Claydol'),
	('Lileep'),('Cradily'),
	('Anorith'),('Armaldo'),
	('Feebas'),('Milotic'),
	('Castform'),
	('Kecleon'),
	('Shuppet'),('Banette'),
	('Duskull'),('Dusclops'),
	('Tropius'),
	('Chimecho'),
	('Absol'),
	('Wynaut'),
	('Snorunt'),('Glalie'),
	('Spheal'),('Sealeo'),('Walrein'),
	('Clamperl'),('Huntail'),
		     ('Gorebyss'),
	('Relicanth'),
	('Luvdisc'),
	('Bagon'),('Shelgon'),('Salamence'),
	('Beldum'),('Metang'),('Metagross'),
	('Regirock'),
	('Regice'),
	('Registeel'),
	('Latias'),
	('Latios'),
	('Kyogre'),
	('Groudon'),
	('Rayquaza'),
	('Jirachi'),
	('Deoxys');

-- Drop & Change constraint when entering data for new region
ALTER TABLE Dex
	DROP CONSTRAINT DF__Dex__Reg_Id__4F7CD00D;

ALTER TABLE Dex  
    ADD CONSTRAINT DF__Dex__Reg_Id__4F7CD00D 
    DEFAULT 4 FOR Reg_Id;

--Region 4 Pokemon name entry, new evolution chain on each row
INSERT INTO dbo.Dex (Pkmn_Name) VALUES
	('Turtwig'),('Grotle'),('Torterra'),
	('Chimchar'),('Monferno'),('Infernape'),
	('Piplup'),('Prinplup'),('Empoleon'),
	('Starly'),('Staravia'),('Staraptor'),
	('Bidoof'),('Bibarel'),
	('Kricketot'),('Kricketune'),
	('Shinx'),('Luxio'),('Luxray'),
	('Budew'),('Roserade'),
	('Cranidos'),('Rampardos'),
	('Shieldon'),('Bastiodon'),
	('Burmy'),('Wormadam'),('Mothim'),
	('Combee'),('Vespiquen'),
	('Pachirisu'),
	('Buizel'),('Floatzel'),
	('Cherubi'),('Cherrim'),
	('Shellos'),('Gastrodon'),
	('Ambipom'),
	('Drifloon'),('Drifblim'),
	('Buneary'),('Lopunny'),
	('Misagius'),
	('Honchkrow'),
	('Glameow'),('Purugly'),
	('Chingling'),
	('Stunky'),('Skuntank'),
	('Bronzor'),('Bronzong'),
	('Bonsly'),
	('Mime.Jr'),
	('Happiny'),
	('Chatot'),
	('Spiritomb'),
	('Gible'),('Gabite'),('Garchomp'),
	('Munchlax'),
	('Riolu'),('Lucario'),
	('Hippopotas'),('Hippowdon'),
	('Skorupi'),('Drapion'),
	('Croagunk'),('Toxicroak'),
	('Carnivine'),
	('Finneon'),('Lumineon'),
	('Mantyke'),
	('Snover'),('Abomasnow'),
	('Weavile'),
	('Magnezone'),
	('Lickilicky'),
	('Rhyperior'),
	('Tangrowth'),
	('Electivire'),
	('Magmortar'),
	('Togekiss'),
	('Yanmega'),
	('Leafeon'),
	('Glaceon'),
	('Gliscor'),
	('Mamoswine'),
	('Porygon-Z'),
	('Gallade'),
	('Probopass'),
	('Dusknoir'),
	('Froslass'),
	('Rotom'),
	('Uxie'),
	('Mesprit'),
	('Azelf'),
	('Dialga'),
	('Palkia'),
	('Heatran'),
	('Regigigas'),
	('Giratina'),
	('Cresselia');

-- Drop & Change constraint when entering data for new region
ALTER TABLE Dex
	DROP CONSTRAINT DF__Dex__Reg_Id__4F7CD00D;

ALTER TABLE Dex  
    ADD CONSTRAINT DF__Dex__Reg_Id__4F7CD00D 
    DEFAULT 10 FOR Reg_Id;

--Region 10 (Unknown) Pokemon name entry, new evolution chain on each row
SET IDENTITY_INSERT Dex ON;
INSERT INTO dbo.Dex (Pkmn_Id,Pkmn_Name) VALUES 
(808,'Meltan'),(809,'Melmetal');
SET IDENTITY_INSERT Dex OFF;



